version: "3"
services:
  ecommercewebsite:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ".env"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - mynetwork
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    networks:
      - mynetwork
networks:
  mynetwork:
